---

- name: installs epel-release.
  yum: name=epel-release

- name: disables epel-release.
  ini_file: dest=/etc/yum.repos.d/epel.repo section=epel
    option=enabled value=0

- name: updates all packages.
  yum: name=* state=latest
