---

- file:
    path: /home/vagrant
    state: directory
    mode: 0755

# TODO fix?
- name: Copy wordpress config file.
  copy:
    src: wp-config.php
    dest: /home/vagrant/wordpress
    mode: a+x
